apiVersion: v1
kind: Pod
metadata:
  name: my-wep-app
  
spec:
  containers:
    - image: meslhy/proj:latest
      name: nginx-container
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      
