on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3


      - name: "login to dockerHub"
        run: docker login --username ${{ secrets.USERNAME}} --password ${{secrets.PASSWORD}}

      - name: "building docker image"
        run: docker build -t ${{ secrets.USERNAME}}/proj .

      - name: "pushing to docker hub"
        run: docker push ${{ secrets.USERNAME}}/proj

